### ISSUE TITLE
Which.js NPM dependency looking for Python2 whereas Python3.6 is required

### ISSUE THREAD

**Issue by kevinlacire** [C-JSN/ID3-React#84]
Hi,

I can't install project dependencies due to this Python dependency checking error :
```bash
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\USERNAME\Downloads\D3-ID3\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\USERNAME\Downloads\D3-ID3\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\USERNAME\Downloads\D3-ID3\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\USERNAME\Downloads\D3-ID3\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\USERNAME\Downloads\D3-ID3\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\USERNAME\Downloads\D3-ID3\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\USERNAME\Downloads\D3-ID3\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\USERNAME\Downloads\D3-ID3\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\USERNAME\Downloads\D3-ID3\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\USERNAME\Downloads\D3-ID3\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\USERNAME\Downloads\D3-ID3\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\USERNAME\Downloads\D3-ID3\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\USERNAME\AppData\Local\Programs\Python\Python36\python.EXE
gyp verb check python version `C:\Users\USERNAME\AppData\Local\Programs\Python\Python36\python.EXE -c "import platform; print(platform.python_version());"` returned: "3.6.1\r\n"
gyp verb could not find "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36\python.EXE". checking python launcher
gyp verb could not find "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36\python.EXE". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\USERNAME\Downloads\D3-ID3\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\USERNAME\Downloads\D3-ID3\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\USERNAME\Downloads\D3-ID3\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\USERNAME\\Downloads\\D3-ID3\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\USERNAME\Downloads\D3-ID3\node_modules\node-sass
gyp ERR! node -v v8.1.3
gyp ERR! node-gyp -v vhttps://registry.npmjs.org/node-gyp/-/node-gyp-3.6.1.tgz
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
I tried to install on both Ubuntu 16.04 and Windows 7 => Same errors

**Comment by pshapiro** [comment]
Receiving the same error.
